---
- name: Holding snapd
  dpkg_selections:
    name: snapd
    selection: hold

- name: Install Generic Packages GUI - Debian
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ os_packages_gui }}"
  when: "{{ os_desktop_enable }}"

- name: Remove Banned Packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ os_banned_packages }}"

- name: Configure 'sudoers' file
  lineinfile:
    dest: /etc/sudoers
    insertafter: "{{ item.regexp}}"
    line: "{{ item.line }}"
    validate: '/usr/sbin/visudo -cf %s'
  with_items:
    - "{{ sudoers_rules }}"

- name: Configure /etc/bash.bashrc
  lineinfile:
    dest: /etc/bash.bashrc
    insertafter: EOF
    line: "{{item}}"
  with_items:
    - "{{ bashrc_alias }}"
