---
- name: Install Generic Pre Reqs - RedHat GUI
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ os_packages_gui }}"
  when: (os_desktop_enable and os_packages_gui)
  
- name: Remove Banned Packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ os_banned_packages }}"
  when:
    - "{{ os_banned_packages }}"

